"""initial schema

Revision ID: e328c3bf2210
Revises: 
Create Date: 2026-09-28 15:28:00.492143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e328c3bf2210'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_spaces', sa.Integer(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('ai_analysis_frequency', sa.String(length=100), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'ACTION_REQUIRED', name='verificationstatus'), nullable=True),
    sa.Column('subscription_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('inspection_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.Enum('RECURRING', 'EVENT_DRIVEN', name='scheduletype'), nullable=False),
    sa.Column('recurrence_type', sa.Enum('DAILY', 'CUSTOM_DAYS', name='recurrencetype'), nullable=False),
    sa.Column('custom_days', sa.String(length=255), nullable=True),
    sa.Column('start_time_minutes', sa.Integer(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_workers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('worker_status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', name='propertyworkerstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_table('spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('space_type', sa.Enum('GUEST_ROOM', 'BEDROOM', 'KITCHEN', 'BAR_COUNTER', 'DINING_AREA', 'OUTDOOR', 'RESTROOM', 'RECEPTION', 'STORAGE', 'OTHER', name='spacetype'), nullable=False),
    sa.Column('floor_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_captures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('space_view_id', sa.String(length=36), nullable=False),
    sa.Column('capture_image_url', sa.Text(), nullable=False),
    sa.Column('capture_status', sa.Enum('PENDING', 'OK', 'REJECTED', name='capturestatus'), nullable=True),
    sa.Column('capture_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['inspection_schedules.id'], ),
    sa.ForeignKeyConstraint(['space_view_id'], ['space_views.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('space_view_id', sa.String(length=36), nullable=False),
    sa.Column('master_image_url', sa.Text(), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['space_view_id'], ['space_views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('issue_status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='issuestatus'), nullable=True),
    sa.Column('issue_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issueseverity'), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['capture_id'], ['inspection_captures.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_tickets')
    op.drop_table('master_images')
    op.drop_table('inspection_captures')
    op.drop_table('space_views')
    op.drop_table('spaces')
    op.drop_table('property_workers')
    op.drop_table('inspection_schedules')
    op.drop_table('user_sessions')
    op.drop_table('properties')
    op.drop_table('subscription_plans')
    op.drop_table('prompts')
    op.drop_table('app_users')
    # ### end Alembic commands ###
